customCommands:
  - key: "<c-g>"
    command: |
      git fetch --prune && git for-each-ref --format '%(HEAD)|%(refname:short)|%(upstream:track)' refs/heads | awk -F'|' '$1 != "*" && $3 == "[gone]" {print $2}' | xargs git branch -D
    context: "global"
    description: "Prune local branches no longer on its remote; (G)one."
    loadingText: "Pruning gone..."
